/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Point;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.apache.commons.validator.routines.UrlValidator;
import struct.*;
import base.*;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class WSOFrame extends javax.swing.JFrame {

    /**
     * Creates new form WSOFrame
     */
    public WSOFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        main_tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        file_manager = new javax.swing.JTable();
        edit_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        save_button = new javax.swing.JButton();
        download_button = new javax.swing.JButton();
        upload_button = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        php_eval_area = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        file_field = new javax.swing.JTextField();
        file_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        eval_result = new javax.swing.JTextArea();
        eval_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        console_output = new javax.swing.JTextArea();
        console_cmd = new javax.swing.JTextField();
        console_button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        server_info = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        url_field = new javax.swing.JTextField();
        go_button = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        logs = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        folder_field = new javax.swing.JTextField();
        folder_button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ip_edit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        host_edit = new javax.swing.JTextField();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vader WSO");

        jPanel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        file_manager.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        file_manager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "File", "Modified", "Permissions"
            }
        ));
        file_manager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickFileManager(evt);
            }
        });
        file_manager.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                file_managerKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(file_manager);
        if (file_manager.getColumnModel().getColumnCount() > 0) {
            file_manager.getColumnModel().getColumn(0).setResizable(false);
        }

        edit_button.setText("Edit");
        edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_buttonActionPerformed(evt);
            }
        });

        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.setEnabled(false);
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        save_button.setText("Save");
        save_button.setEnabled(false);
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        download_button.setText("Download");
        download_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                download_buttonActionPerformed(evt);
            }
        });

        upload_button.setText("Upload");
        upload_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1212, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(download_button, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upload_button, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_button)
                    .addComponent(delete_button)
                    .addComponent(cancel_button)
                    .addComponent(save_button)
                    .addComponent(download_button)
                    .addComponent(upload_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_tabs.addTab("FileManager", jPanel1);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Code:");

        php_eval_area.setColumns(20);
        php_eval_area.setRows(5);
        jScrollPane3.setViewportView(php_eval_area);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("File:");
        jLabel5.setToolTipText("");

        file_button.setText(">>");
        file_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_buttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Result:");

        eval_result.setEditable(false);
        eval_result.setColumns(20);
        eval_result.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        eval_result.setRows(5);
        jScrollPane4.setViewportView(eval_result);

        eval_button.setText("Выполнить");
        eval_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eval_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(file_field, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(file_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eval_button))
                        .addGap(0, 265, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(file_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(file_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(eval_button)
                .addContainerGap())
        );

        main_tabs.addTab("PHP", jPanel7);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Output:");

        console_output.setEditable(false);
        console_output.setColumns(20);
        console_output.setRows(5);
        jScrollPane5.setViewportView(console_output);

        console_cmd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        console_cmd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                console_key_pressed(evt);
            }
        });

        console_button.setText(">>");
        console_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                console_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1212, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(console_cmd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(console_button)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(console_cmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(console_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_tabs.addTab("Console", jPanel3);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Server Info:");

        server_info.setColumns(20);
        server_info.setRows(5);
        jScrollPane6.setViewportView(server_info);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1212, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        main_tabs.addTab("Info", jPanel4);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("GUI Shell :)");

        jLabel2.setText("URL:");

        url_field.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        url_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                url_fieldActionPerformed(evt);
            }
        });

        go_button.setText("GO!");
        go_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_buttonActionPerformed(evt);
            }
        });

        logs.setEditable(false);
        logs.setColumns(20);
        logs.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        logs.setRows(5);
        logs.setText("Добро пожаловать в Vader WSO\n");
        jScrollPane2.setViewportView(logs);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Folder:");

        folder_button.setText(">>");
        folder_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folder_buttonActionPerformed(evt);
            }
        });

        jLabel9.setText("IP:");

        ip_edit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel10.setText("HOSTNAME:");

        host_edit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(main_tabs)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(folder_field, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(folder_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ip_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(url_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(go_button, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(host_edit)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(go_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(url_field, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(folder_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(folder_button)
                    .addComponent(jLabel9)
                    .addComponent(ip_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(host_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(main_tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        main_tabs.getAccessibleContext().setAccessibleName("main_tabs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void file_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_buttonActionPerformed
        JFileChooser fileopen = new JFileChooser();
        fileopen.setCurrentDirectory(new File("."));
        int ret = fileopen.showDialog(null, "Открыть файл");
        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fileopen.getSelectedFile();
            String path = file.getAbsolutePath();
            if (path.indexOf(".php") < 0) {
                JOptionPane.showMessageDialog(null, "Файл должен иметь расширение .php");
            } else {
                file_field.setText(path);
            }
        }
    }//GEN-LAST:event_file_buttonActionPerformed

    private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_buttonActionPerformed
        int row = this.file_manager.getSelectedRow();

        if (row < WebWSO.folders.size()) {
            Helper.log("Не могу редактировать директорию");
        } else {
            OneFile fl = WebWSO.files.get(row - WebWSO.folders.size());
            WebWSO web_wso = new WebWSO();
            web_wso.action = 7;
            web_wso.file = fl.name;
            web_wso.start();
            this.save_button.setEnabled(true);
            this.cancel_button.setEnabled(true);
        }
    }//GEN-LAST:event_edit_buttonActionPerformed

    private void file_managerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_file_managerKeyPressed
        //System.out.println(evt.getKeyCode());
        int row = this.file_manager.getSelectedRow();
        if (evt.getKeyCode() == 10) {
            if (row < WebWSO.folders.size()) {
                WebWSO web_wso = new WebWSO();
                web_wso.action = 1;
                web_wso.dir = WebWSO.folders.get(row).name;
                web_wso.start();
            } else {
                OneFile fl = WebWSO.files.get(row - WebWSO.folders.size());
                WebWSO web_wso = new WebWSO();
                web_wso.action = 2;
                web_wso.file = fl.name;
                web_wso.start();
            }
        }
    }//GEN-LAST:event_file_managerKeyPressed

    private void clickFileManager(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickFileManager
        JTable table = (JTable) evt.getSource();
        Point point = evt.getPoint();
        int row = table.rowAtPoint(point);
        if (evt.getClickCount() == 2 && table.getSelectedRow() != -1) {
            if (row < WebWSO.folders.size()) {
                WebWSO web_wso = new WebWSO();
                web_wso.action = 1;
                web_wso.dir = WebWSO.folders.get(row).name;
                web_wso.start();
            } else {
                OneFile fl = WebWSO.files.get(row - WebWSO.folders.size());
                WebWSO web_wso = new WebWSO();
                web_wso.action = 2;
                web_wso.file = fl.name;
                web_wso.start();
            }
        }
    }//GEN-LAST:event_clickFileManager

    private void upload_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_buttonActionPerformed
        JFileChooser fileopen = new JFileChooser();
        fileopen.setCurrentDirectory(new File("."));
        int ret = fileopen.showDialog(null, "Выбрать загружаемый файл");
        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fileopen.getSelectedFile();
            String path = file.getAbsolutePath();
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Собираемся вгрузить '" + path + "', продолжить?", "Подтверждение", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                WebWSO web_wso = new WebWSO();
                web_wso.action = 3;
                web_wso.file = path;
                web_wso.dir = this.folder_field.getText();
                web_wso.start();
            }
        }
    }//GEN-LAST:event_upload_buttonActionPerformed

    private void go_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_buttonActionPerformed
        String url = url_field.getText();
        Pattern p_host = Pattern.compile("://(.*?)/", Pattern.CASE_INSENSITIVE);
        Matcher m_host = p_host.matcher(url + "/");
        if (!m_host.find()) {
            JOptionPane.showMessageDialog(null, "Неверный формат URL");
            return;
        }
        //
        String host = m_host.group(1);
        String h = Helper.replace(host.toLowerCase(), "www.", "");
        String[] hh = h.split("\\.");
        String hostname = hh[0];

        String ip = "127.0.0.1";

        try {
            InetAddress adr = java.net.InetAddress.getByName(host);
            ip = adr.getHostAddress();
        } catch (Exception ex) {
            Logger.getLogger(WSOFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (ip_edit.getText().isEmpty()) {
            ip_edit.setText(ip);
        }
        if (host_edit.getText().isEmpty()) {
            host_edit.setText(host);
        }


        UrlValidator urlValidator = new UrlValidator();

        if (url.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Не указан URL");
            return;
        }

        //if (!urlValidator.isValid(url)) {
        //    JOptionPane.showMessageDialog(null, "Некорректно задан URL");
        //    return;
        //}
        WebWSO.url = url;
        WebWSO web_wso = new WebWSO();
        web_wso.action = 0;
        web_wso.start();

    }//GEN-LAST:event_go_buttonActionPerformed

    private void folder_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folder_buttonActionPerformed
        String dir = this.folder_field.getText();
        WebWSO web_wso = new WebWSO();
        web_wso.action = 1;
        web_wso.dir = dir;
        web_wso.start();
    }//GEN-LAST:event_folder_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        int row = this.file_manager.getSelectedRow();
        if (row < WebWSO.folders.size()) {
            String path = WebWSO.folders.get(row).name;
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Удаляем директорию '" + path + "', продолжить?", "Подтверждение", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                WebWSO web_wso = new WebWSO();
                web_wso.action = 4;
                web_wso.dir = path;
                web_wso.start();
            }
        } else {
            OneFile fl = WebWSO.files.get(row - WebWSO.folders.size());
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Удаляем файл '" + fl.name + "', продолжить?", "Подтверждение", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                WebWSO web_wso = new WebWSO();
                web_wso.action = 5;
                web_wso.file = fl.name;
                web_wso.start();
            }
        }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void download_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_download_buttonActionPerformed
        int row = this.file_manager.getSelectedRow();

        if (row < WebWSO.folders.size()) {
            Helper.log("Не могу скачать директорию");
        } else {
            OneFile fl = WebWSO.files.get(row - WebWSO.folders.size());
            WebWSO web_wso = new WebWSO();
            web_wso.action = 6;
            web_wso.file = fl.name;
            web_wso.start();
        }

    }//GEN-LAST:event_download_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Отменить изменения '" + WebWSO.edit_file + "'?", "Подтверждение", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            WebWSO.edit_dir = null;
            WebWSO.edit_file = null;
            this.cancel_button.setEnabled(false);
            this.save_button.setEnabled(false);
        }
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void eval_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eval_buttonActionPerformed
        String code = this.php_eval_area.getText().trim();
        String filepath = this.file_field.getText();
        if (!filepath.isEmpty()) {
            code = Helper.readFile(filepath);
            code = Helper.replace(code, "<?php", "");
            code = Helper.replace(code, "?>", "");
            code = code.trim();
        }

        if (code.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Не указан ни код, ни php файл!");
            return;
        }

        WebWSO web_wso = new WebWSO();
        web_wso.action = 9;
        web_wso.code = code;
        web_wso.start();
    }//GEN-LAST:event_eval_buttonActionPerformed

    private void console_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_console_buttonActionPerformed
        String cmd = this.console_cmd.getText();
        if (cmd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Не указана консольная команда!");
            return;
        }

        WebWSO web_wso = new WebWSO();
        web_wso.action = 10;
        web_wso.code = cmd;
        web_wso.start();
    }//GEN-LAST:event_console_buttonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Сохранить изменения '" + WebWSO.edit_file + "'?", "Подтверждение", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            WebWSO web_wso = new WebWSO();
            web_wso.action = 8;
            web_wso.start();
            this.cancel_button.setEnabled(false);
            this.save_button.setEnabled(false);
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void console_key_pressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_console_key_pressed
        if (evt.getKeyCode() == 10) {
            this.console_buttonActionPerformed(null);
        }
    }//GEN-LAST:event_console_key_pressed

    private void url_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_url_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_url_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WSOFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WSOFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WSOFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WSOFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WSOFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancel_button;
    public javax.swing.JButton console_button;
    public javax.swing.JTextField console_cmd;
    public javax.swing.JTextArea console_output;
    public javax.swing.JButton delete_button;
    public javax.swing.JButton download_button;
    public javax.swing.JButton edit_button;
    public javax.swing.JButton eval_button;
    public javax.swing.JTextArea eval_result;
    public javax.swing.JButton file_button;
    public javax.swing.JTextField file_field;
    public javax.swing.JTable file_manager;
    public javax.swing.JButton folder_button;
    public javax.swing.JTextField folder_field;
    public javax.swing.JButton go_button;
    public static javax.swing.JTextField host_edit;
    public static javax.swing.JTextField ip_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextArea logs;
    public javax.swing.JTabbedPane main_tabs;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    public javax.swing.JTextArea php_eval_area;
    public javax.swing.JButton save_button;
    public javax.swing.JTextArea server_info;
    public javax.swing.JButton upload_button;
    public javax.swing.JTextField url_field;
    // End of variables declaration//GEN-END:variables
}
